### PR TITLE
Upgrade atlas version to support + separator in version

### PR DESCRIPTION
**Pull request by yma88**

### CODE REVIEW

**Review by ligangty — COMMENTED** [review]
@yma88 This looks good. I think we can merge it.
BTW, Seems we have a new issue of log level problem https://github.com/release-engineering/offliner/issues/71 Can you help have a look?

**Comment by yma88** [comment]
@ligangty, OK, I'll check that issue, and for this I'll merge once atlas 1.1.2 is delivered.

**Comment by ligangty** [comment]
@yma88 are there any blockers for atlas 1.1.2 release?

**Comment by yma88** [comment]
@ligangty I've no access to tag release version, talked with liyu, she could

**Pull request merged**
